name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20, 22, 24]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run all checks
        run: npm run check
      
      - name: Run build
        run: npm run build
      
      - name: Check build output
        run: |
          ls -la dist/
          echo "Build files:"
          find dist/ -type f -name "*.js" -o -name "*.d.ts" -o -name "*.map" | sort
      
      - name: Verify pm2 is external
        run: |
          echo "Checking that pm2 is not bundled..."
          # Check that pm2 is properly externalized (should find external require/import references)
          if ! grep -q "require(\"pm2\")" dist/index.cjs.js; then
            echo "ERROR: pm2 external require not found in CJS build!"
            exit 1
          fi
          if ! grep -q 'import pm2 from "pm2"' dist/index.esm.js; then
            echo "ERROR: pm2 external import not found in ESM build!"
            exit 1
          fi
          # Check that pm2 is not bundled (should not find pm2 module code in the bundle)
          if grep -q "pm2\.connect\|pm2\.list\|pm2\.start" dist/index.cjs.js && ! grep -q "require(\"pm2\")" dist/index.cjs.js; then
            echo "ERROR: pm2 appears to be bundled in CJS build!"
            exit 1
          fi
          if grep -q "pm2\.connect\|pm2\.list\|pm2\.start" dist/index.esm.js && ! grep -q 'import pm2 from "pm2"' dist/index.esm.js; then
            echo "ERROR: pm2 appears to be bundled in ESM build!"
            exit 1
          fi
          echo "✅ pm2 correctly externalized (not bundled)"
