name: Deploy Documentation to GitHub Pages

# Only run when documentation or related files change
on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'                              # Documentation files
      - 'scripts/**'                           # Version sync scripts
      - 'package.json'                         # Version changes
      - '.github/workflows/deploy-docs.yml'    # Workflow changes
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'                              # Documentation files
      - 'scripts/**'                           # Version sync scripts
      - 'package.json'                         # Version changes

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Build library
        run: npm run build:prod

      - name: Validate docs
        run: |
          echo "Validating documentation files..."
          if [ ! -f "docs/index.html" ]; then
            echo "Error: docs/index.html not found"
            exit 1
          fi
          if [ ! -f "docs/styles.css" ]; then
            echo "Error: docs/styles.css not found"
            exit 1
          fi
          if [ ! -f "docs/script.js" ]; then
            echo "Error: docs/script.js not found"
            exit 1
          fi
          echo "✅ All documentation files present"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
